PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wds: <http://www.wikidata.org/entity/statement/>
PREFIX wdv: <http://www.wikidata.org/value/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bd: <http://www.bigdata.com/rdf#>
# -------------------------------------
#added before 2016-10
#Illustrates optional fields, instances of subclasses, language fallback on label service, date to year conversion
# Chevaux sur Wikidata
SELECT DISTINCT ?cheval ?mere ?pere (year(?naissance) as ?Naissance) (year(?deces) as ?Décès)
WHERE
{
	?cheval wdt:P31/wdt:P279* wd:Q726 .     # Instance et sous-classes de Q726-Cheval
	 
	OPTIONAL{?cheval wdt:P25 ?mere .}       # P25  : Mère
	OPTIONAL{?cheval wdt:P22 ?pere .}       # P22  : Père
	OPTIONAL{?cheval wdt:P569 ?naissance .} # P569 : Date de naissance
	OPTIONAL{?cheval wdt:P570 ?deces .}     # P570 : Date de décès
	OPTIONAL{?cheval wdt:P21 ?sexe .}       # P21  : Sexe
 
}
ORDER BY ?cheval
