# -------------------------------------
PREFIX schema: <http://schema.org/>

SELECT ?sitelink
WHERE 
{
  BIND(wd:Q52 AS ?wikipedia)
  ?sitelink schema:about ?wikipedia .
  FILTER REGEX(STR(?sitelink), ".wikipedia.org/wiki/") .
}
