# -------------------------------------
#defaultView:BubbleChart
#TEMPLATE={ "template": "The top 10 heaviest ?type ", "variables": { "?type": { "query": "SELECT DISTINCT ?id WHERE { ?i wdt:P2067 ?v. ?i wdt:P31 ?id}" } } }
SELECT ?item ?itemLabel ?mass ?image WHERE {
  BIND(wd:Q5 AS ?type)
  ?item wdt:P31 ?type;
        p:P2067/psn:P2067/wikibase:quantityAmount ?mass.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,es,fr,de" }
}
ORDER BY DESC(?mass)
LIMIT 10
