# -------------------------------------
#defaultView:Map
SELECT ?objectLabel ?objectDescription ?link ?coord
WHERE {
  ?object wdt:P31/wdt:P279? wd:Q46169 ;
          wdt:P856 ?link ;
          wdt:P625 ?coord .
          SERVICE wikibase:label {
               bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,fr"
          }
}
