# -------------------------------------
#defaultView:ScatterChart
SELECT ?from (?distGrp1 AS ?kilometers) ?to WHERE {
  BIND(wd:Q15284 AS ?muntype).
  BIND(wd:Q6308 AS ?area).
  ?mun wdt:P31/wdt:P279* ?muntype;
       wdt:P131 ?area;
       wdt:P625 ?loc.
  OPTIONAL { ?mun2 wdt:P31/wdt:P279* ?muntype;
                   wdt:P131 ?area;
                   wdt:P625 ?loc2. }
  BIND(geof:distance(?loc, ?loc2) AS ?distNum).
  BIND(STR(ROUND(?distNum)) AS ?distGrp0).
  BIND(CONCAT(SUBSTR("000",STRLEN(?distGrp0)+1),?distGrp0,".",STR(ROUND((?distNum-FLOOR(?distNum))*10))," km") AS ?distGrp1).

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en".
    ?mun rdfs:label ?from.
    ?mun2 rdfs:label ?to.
  }
}
ORDER BY ?from ?kilometers
