PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wds: <http://www.wikidata.org/entity/statement/>
PREFIX wdv: <http://www.wikidata.org/value/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bd: <http://www.bigdata.com/rdf#>
# -------------------------------------
#added before 2016-10

#defaultView:Map
SELECT ?p ?location ?el ?image
WHERE
{
  ?p p:P2044/psv:P2044 ?pel.
  ?pel wikibase:quantityAmount ?el.
  ?pel wikibase:quantityUnit ?unit.
  bind(0.01 as ?km).
  filter( (?el < ?km*1000 && ?unit = wd:Q11573) ||
         (?el < ?km*3281 && ?unit = wd:Q3710)
       || (?el < ?km && ?unit = wd:Q828224) ).
  ?p wdt:P625 ?location.
  optional { ?p wdt:P18 ?image }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
